### ISSUE TITLE
Failed to import MatBasicSpinnerDirective in Angular v18.

### ISSUE THREAD

**Issue by jordankkk** [dkreider/ngx-loading-buttons#28]
Cannot import MatBasicSpinnerDirective or NgxLoadingButtonsModule with Angular v18 standalone.

```bash
error TS2307: Cannot find module 'ngx-loading-buttons' or its corresponding type declarations.
```

```json
"ngx-loading-buttons": "^18.0.0"
"typescript": "^5.4.2"
"@angular/core": "^18.0.1",
```

**Comment by iamjustanotherrandom** [comment]
Same happens for me, it seems that something is wrong with v18 version of the library, here is an example of the issue in [Stackblitz](https://stackblitz.com/edit/stackblitz-starters-9vtdgd?file=src%2Fapp%2Fapp.component.ts)

**Comment by Totto16** [comment]
If you look at the content of the package, you see, that 18.0.0 is empty, see e.g. [here](https://www.npmjs.com/package/ngx-loading-buttons/v/18.0.0?activeTab=code) 

if you look at previous versions, you can see, that it has the correct content see e.g. [here](https://www.npmjs.com/package/ngx-loading-buttons/v/17.0.2?activeTab=code)
