### ISSUE TITLE
The style is not working anymore

### ISSUE THREAD

**Issue by fwautriche** [dkreider/ngx-loading-buttons#6]
Hello,

I was using [your css style](https://dkreider.medium.com/how-to-add-a-spinner-to-an-angular-material-button-the-simplest-way-ever-69e2f7005f29) in my application but it doesn't seem to work anymore.
The last thing I did is to upgrade my project to Angular 14 but I also suspect that something is not working with my latest browser version.
I tried to use your package but with no success :(

[Tests made with Stackblitz](https://angular-qvhkws.stackblitz.io) on older version of Angular does not work either.

Am I missing something?

Thanks in advance!

**Comment by fwautriche** [comment]
Another message to exclude that the problem is coming from the Browser.

I just test my application in the production environment (with Angular 13) and the spinner is displayed. While in the test environment (with Angular 14) the spinner is no longer displayed.

However, the problem is probably due to Angular **Material** 14 rather than Angular 14 itself.

**Comment by tux1337** [comment]
I can confirm this issue in my environment too. 
After upgrading to Angular 14, the spinner is not working any more (not shown).

**Comment by dkreider** [comment]
Hey @fwautriche @tux1337 

Thanks for reporting this!

I just published the fix and will go ahead and close this issue. 

If you have any problems don't hesitate to re-open or file a new issue.

**Comment by r-oleary** [comment]
I'm using this in Angular 14 and it's not working for me. No errors anywhere, but I don't see a spinner. FWIW, I was doing this without this component (using the css class like the original article described), and that stopped working in v14 as well. I'm trying this component as a solution, but it's not working either.

**Comment by fwautriche** [comment]
I also directly use the style.

I apply the same fix as @dkreider did in the component.

I change `.spinner:before` to `.spinner:after` and it works again.

Hope this help.
